# Generated by Django 3.0.8 on 2020-07-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20200719_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='FK_Materia',
        ),
        migrations.AddField(
            model_name='professor',
            name='FK_Materia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='escola.Materia'),
            preserve_default=False,
        ),
    ]
