# Generated by Django 3.0.8 on 2020-07-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20200720_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='FK_Func_Prof',
            new_name='Funcionario',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='FK_Materia',
            new_name='Materia',
        ),
    ]
