# Generated by Django 3.0.8 on 2020-07-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20200721_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='numero_cracha',
        ),
    ]
