# Generated by Django 3.0.8 on 2020-07-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_remove_coordenador_numero_cracha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='FK_Turma',
            new_name='Turma',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='FK_Coordenador',
            new_name='Coordenador',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='FK_Prof_Turma',
            new_name='Professores',
        ),
    ]
