# Generated by Django 3.0.8 on 2020-07-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_auto_20200721_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='dt_nasc',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='nome_aluno',
            new_name='nome_do_aluno',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='dt_nasc',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_funcionario',
            new_name='nome_do_funcionario',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='nome_materia',
            new_name='nome_da_materia',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='numero_aulas',
            new_name='numero_de_aulas',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='letra_turma',
            new_name='letra_da_turma',
        ),
    ]
